### ISSUE TITLE
Closing most games causes a nucleus coop silent crash

### ISSUE THREAD

**Issue by SirGouki** [SplitScreen-Me/splitscreenme-nucleus#10]
I have tested this with Earth Defense Force 5, and Dark Souls 3.

Closing out all instances of these games through the game itself will cause nucleus coop to silently crash.  Using Ctrl + D to stop nucleus will sometimes also cause this crash, but closing out the games manually does *every* time.

Version info:
Dark Souls 3: latest
ds3os build v0.18.0.0-main
EDF5: latest

**Comment by Mikou27** [comment]
Thank you very much for your report.
