### ISSUE TITLE
Some Weird Monitor Order Crap

### ISSUE THREAD

**Issue by Swandar** [SplitScreen-Me/splitscreenme-nucleus#105]
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### Bug description

I use my primary monitors for more than just my PC, I used them for my xbox and ps5 as well,
This is a bug that has existed for at least very long time and I am really just surprised that the option to manually change the index hasn't been added

D3ATHCOM5 is supposed to be on the bigger monitor while Kitty is supposed to be where D3ATHCOM5 is

![Screenshot 2024-11-22 111123](https://github.com/user-attachments/assets/8608aca9-4990-43bf-ba6c-ee38e17a74ae)

This issue happened after switching over to my ps5 to play spiderman and for some reason, it broke all my profiles in Nucleuscoop,
So now I have to delete dozens of profiles and recreate them

![Screenshot 2024-11-22 111504](https://github.com/user-attachments/assets/6c64b241-17cf-46c0-8524-64a4495d0cb5)
![Screenshot 2024-11-22 111735](https://github.com/user-attachments/assets/e888d7a0-e3d5-4b5d-a2e8-274d5e506f51)

Big screen is clearly screen one (index 0), but after using my ps5 it's gone from Index 0 to Index 2 in your software, if I knew where you stored files that store this info I could just fix it without having to spend a few hours deleting profiles, relaunching games, saving new profiles, etc etc

### Debug Log

I can't provide one as there isn't one

### Possible fixes or solutions

Add the ability to change monitor launch order/which monitor is player1,2,3,etc, monitor index

EDIT: Changed index 3 to 2, typo

**Comment by Swandar** [comment]
So it turns out, it didn't just break the screen index, it broke inputs as well, I can't click on anything.
Where are the core files located so I can delete them? I already tried reinstalling, but whatever config files that store the data for screen information isn't in the primary directory

**Comment by Mikou27** [comment]
Screen indexes are assigned by Windows not Nucleus so there's no files to edit.

You can edit the profiles manually, that's the only files in use here, or try to make Windows to reassign the display indexes like they were before they get messed up.
