### ISSUE TITLE
📇 Discord invite links invalid

### ISSUE THREAD

**Issue by FossiFoo** [SplitScreen-Me/splitscreenme-nucleus#106]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Issue

All discord invite links I could find are invalid: On the app, on github, on the homepage, in the subreddit (faq).

**Comment by Snailedlt** [comment]
Again?!
I just replaced them like 2 months ago.


Could you link to the places or screenshot where the invite links stopped working?

Also here's a working link: https://discord.gg/qnbZtpECYg

**Comment by FossiFoo** [comment]
Weird, that link also does not work for me on desktop but it did work on mobile? ![image](https://github.com/user-attachments/assets/1b7f0b75-3f6c-46e7-ae56-76cf14a75180)

Either way, thanks.

**Comment by Snailedlt** [comment]
@FossiFoo that's very odd. It works for me, so I think this is an issue on your side.

You could try to see if any of these work: 
https://discord.gg/E5B6jAX79f
https://discord.gg/QDUt8HpCvr
