### ISSUE TITLE
🐛 <bug name>打开tModLoader时，nucleuscoop只会打开一个实例然后崩溃闪退

### ISSUE THREAD

**Issue by 459597501** [SplitScreen-Me/splitscreenme-nucleus#107]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

When I opened tModLoader, Nucleascop only opened one instance and then crashed and crashed, unable to open the second instance. I checked D: \ anzhuangbao \ nucleus \ content \ tModLoader \ instance1, which was blank. I confirmed that my controller had no problem and was the latest version. I tried rolling back the version to 2.2.1 but still couldn't solve it because I haven't encountered this situation when starting other games. Only tModLoader experiences this situation. I copied the file of D: \ ncleus \ content \ tModLoader \ instance0 to D: \ anzhuangbao \ nucleus \ content \ tModLoader \ instance0. Sometimes I start normally, but the controller loses its function in the second instance.

### Debug Log

[debug-log.txt](https://github.com/user-attachments/files/17994626/debug-log.txt)

**Comment by 459597501** [comment]
?

**Comment by Mikou27** [comment]
Hi, you can ask for help on our discord or subreddit.
