### ISSUE TITLE
🐛 When I opened tModLoader, Nucleascop only opened one instance and then crashed and crashed, unable to open the second instance

### ISSUE THREAD

**Issue by 459597501** [SplitScreen-Me/splitscreenme-nucleus#109]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

When I opened tModLoader, Nucleascop only opened one instance and then crashed and crashed, unable to open the second instance. I checked D: \ anzhuangbao \ nucleus \ content \ tModLoader \ instance1, which was blank. I confirmed that my controller had no problem and was the latest version. I tried rolling back the version to 2.2.1 but still couldn't solve it because I haven't encountered this situation when starting other games. Only tModLoader experiences this situation. I copied the file of D: \ ncleus \ content \ tModLoader \ instance0 to D: \ anzhuangbao \ nucleus \ content \ tModLoader \ instance0. Sometimes I start normally, but the controller loses its function in the second instance.

### Debug Log

[debug-log.txt](https://github.com/user-attachments/files/18053430/debug-log.txt)

**Comment by 459597501** [comment]
Why was my question closed when no one replied on how to solve it.

**Comment by SteveCraft1** [comment]
I might be wrong but i think this issues page is related to nucleuscoop in general instead of being related to handlers, there's a discord server where you could try saying this issue there if no one appears here to help you(i don't have the game nor the handler to help you)
