### ISSUE TITLE
Missing file(s)

### ISSUE THREAD

**Issue by Beckybeans** [SplitScreen-Me/splitscreenme-nucleus#13]
when launching the program I get a message saying ProtoInputHooks64.dll is missing from installation folder.
I've tried deleting all the folders and redownloading several times and that has not fixed the issue, I can't seem to find the app itself to uninstall it.
I have also updated microsoft.net framework

**Comment by Mikou27** [comment]
Documented in the FAQ not a bug.

**Comment by Snailedlt** [comment]
> Not a bug. 

@Mikou27 
Is this the issue with windows defender deleting files?
If so, maybe point him in the right direction?

**Comment by Mikou27** [comment]
If we want that place to become a mess like in the past then yes we should help peoples here, else we can keep it clean for app bug reports.

**Comment by Snailedlt** [comment]
@Mikou27 True.

@Beckybeans Please read our FAQ on https://splitscreen.me for this issue. If you can't find it, ask for help on our Discord server or our subreddit
