### ISSUE TITLE
"Process Select" menu hides last 2 processes if list is too long

### ISSUE THREAD

**Issue by dude98** [SplitScreen-Me/splitscreenme-nucleus#15]
the select and refresh buttons hide the last two processes if the list is too long, it also hides part of the scroll wheel.

easily reproducible:
1. open a bunch of processes
2. open a game that uses the process selector (MultiMC/Minecraft)
3. javaw sometimes can't be selected because it's hidden under the buttons, and if you use the arrow keys you can go past the last visible option by two selections, scrolling back up into view takes only 2 up presses if you're at the bottom of the list.

**Comment by Mikou27** [comment]
Hi, are you using v2.1.1 https://github.com/SplitScreen-Me/splitscreenme-nucleus/releases/tag/v2.1.1 ? Is your desktop scale set to 100%? 
Thank you for the report.

**Comment by dude98** [comment]
i just downloaded it less than a week ago so yes, and my scale is auto set to 100.
if it does help, i have 3 screens if that might matter. all 3 do it.

**Comment by Snailedlt** [comment]
Like poundlandbacon mentioned on Discord, I think adding a scrollbar would be a nice and simple fix for this issue.

**Comment by Mikou27** [comment]
Fixed.
