### ISSUE TITLE
Add default value for Game.Options

### ISSUE THREAD

**Issue by Snailedlt** [SplitScreen-Me/splitscreenme-nucleus#16]
It would be great if we could add a default value for the textfields.
What I mean by this, is that it would be nice if the textfield could be pre-populated with some text defined in the handler itself.

This would be great for things like launch arguments, where we might have some default launch arguments, that the user should be able to change.

**Comment by Mikou27** [comment]
https://github.com/SplitScreen-Me/splitscreenme-nucleus/pull/61

**Comment by Mikou27** [comment]
https://github.com/SplitScreen-Me/splitscreenme-nucleus/pull/61
