### ISSUE TITLE
Add placeholder text for Game.Options

### ISSUE THREAD

**Issue by Snailedlt** [SplitScreen-Me/splitscreenme-nucleus#17]
This is related to issue #16 

Sometimes, when you have a text field in Game.Options, you want to give a hint to the user as to what are valid inputs. In these cases it would be nice to have a little placeholder text to show a hint as to what they should input.

HTML has this exact feature, and it's widely used for forms where users input stuff like username, phone numbers, emails, etc... to show the user what the text should look like.

Here's an example: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

Notice the greyed out text:
![image](https://user-images.githubusercontent.com/43886029/171911473-9fdbb39f-5381-4ab4-a8a5-d0d38d61d47f.png)

Once you start writing the text disappears:
![image](https://user-images.githubusercontent.com/43886029/171911615-7efc6ce2-7b01-418b-8226-0a843f0e3f3b.png)

and if you submit with just the placeholder text, nothing should be sent:
![image](https://user-images.githubusercontent.com/43886029/171911753-cf115d27-83c7-4685-ae97-50c0f21bf955.png)

Here's a little code snippet I found for implementing this in Winforms:
https://stackoverflow.com/a/21439310/12206312

**Comment by Mikou27** [comment]
https://github.com/SplitScreen-Me/splitscreenme-nucleus/pull/61

**Comment by Mikou27** [comment]
https://github.com/SplitScreen-Me/splitscreenme-nucleus/pull/61
