### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Tizibinki** [SplitScreen-Me/splitscreenme-nucleus#18]
I downloaded the newest verion, put it in C:\Nucleus and tried to start NucleusCoop.exe but nothing is happening. It seems like it tries to load something but it doesn't even open a window.

**Comment by Snailedlt** [comment]
Probably an issue with your antivirus deleting/blocking some of the files.

This is not the right place for support questions.
Read the [FAQ](https://www.splitscreen.me/docs/faq), and ask in our [Discord Server](https://discord.gg/a9ssM5pxTW) if you need more help with it.
