### ISSUE TITLE
✨  Steam DRM authentication mirroring

### ISSUE THREAD

**Issue by mirh** [SplitScreen-Me/splitscreenme-nucleus#29]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

Potential Goldberg alternative solution. 

### Possible Solution

As I already asked back in https://github.com/lucasassislar/nucleuscoop/issues/23, it should be possible with some tinkering to just replay the authentication token that worked for the first instance of a game, on all the subsequent ones. 

### Additional information

Hoping this is the right fork of nucleus.

**Comment by Snailedlt** [comment]
Could you provide some more info? 
Specifically on what the benefit to going this route would be

**Comment by mirh** [comment]
That you wouldn't have to use 3rd party software. 
Also, I guess you could save 100MB of space and a lot of the bother of virus false positives.

**Comment by Mikou27** [comment]
Changed wording for obvious reasons. Don't seems to be a viable alternative for a lot of reasons.

**Comment by mirh** [comment]
I don't know what's obvious, nor what would have been the problem anyway. 
You aren't doing anything *wrong*, but it's not even super clear cut enough that if a troll sent a take down request you could shrug it off with a "lmao you wished". 

Besides, ***especially*** if all of this was the case, then it's even more of a reason to justify my idea (which alas I'll grant is devoid of any actual technical detail, but I checked the theory with Cyanic back in the days, so)

**Comment by Mikou27** [comment]
Not obvious for you maybe, could be for others just a pov. You're welcome to provide more details about the advantages of the suggested method, i did close the issue not deleted it btw. Any details and working examples are welcome. And thank you for the suggestion.

**Comment by mirh** [comment]
The advantages of the method is that (in theory) you don't need external/extra tools to launch multiple steam games. 
I don't know what else there is to explain. 

Depending on how smooth/light/quick/stable/redistributable these already are, the switch could come with more or less pros, but it's not just me having a case of not invented here syndrome.

**Comment by mirh** [comment]
Possibly related
https://github.com/m4dEngi/RemotePlayWhatever
