### ISSUE TITLE
✨Grim Dawn - GrimInternals Support

### ISSUE THREAD

**Issue by draconixx** [SplitScreen-Me/splitscreenme-nucleus#31]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

Is it possible for grim dawn's handler to also work for grim internals (https://forums.crateentertainment.com/t/tool-grim-internals/38773)?

**Comment by Snailedlt** [comment]
This isn't an app feature, but a handler feature and therefore doesn't belong on this GitHub repo.

Instead ask either on our subreddit or discord server
