### ISSUE TITLE
So, am trying to download the file and it asks for a password?, i dont know what password

### ISSUE THREAD

**Issue by GeneralVenus** [SplitScreen-Me/splitscreenme-nucleus#32]

**Comment by Snailedlt** [comment]
`nucleus`
You can always see the password on the release page

**Comment by deoxal** [comment]
But why is there a password?

**Comment by Snailedlt** [comment]
> But why is there a password?

Because Nucleus incorrectly gets flagged as a virus. Having a password circumvents that.

**Comment by deoxal** [comment]
Ah thanks
