### ISSUE TITLE
I DON'T THING IT A BUG BUT TROUBLE ON MY END

### ISSUE THREAD

**Issue by Awaapito** [SplitScreen-Me/splitscreenme-nucleus#40]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Well i cant access any other game
![bruh the forest](https://user-images.githubusercontent.com/100304309/196240530-11fb0ab8-b489-4b78-9e04-99e4a65c118f.png)

### Debug Log

[debug-log.txt](https://github.com/SplitScreen-Me/splitscreenme-nucleus/files/9803018/debug-log.txt)

### Possible fixes or solutions

no clue

### Additional information

Any help please im trying on my end

**Comment by Mikou27** [comment]
Hi, ask for support on the Discord https://discord.com/invite/QDUt8HpCvr server or the subreddit https://www.reddit.com/r/nucleuscoop/ .
