### ISSUE TITLE
✨ Linux support

### ISSUE THREAD

**Issue by dilirity** [SplitScreen-Me/splitscreenme-nucleus#41]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

With the Steam Deck, having support for linux would be great!

This will make it easier to play coop games that require mouse and keyboard.

**Comment by Mikou27** [comment]
Hi, writing a brain new app is required for linux and there is no plan about such thing so far. You can try a dual boot Windows(10/11)/Linux on the steam deck some Nucleus users did it successfully already.
https://discord.com/channels/142649962839277568/705556112778461284/1024848779079331870 
https://discord.com/channels/142649962839277568/705556112778461284/1003304326908878908

**Comment by Mikou27** [comment]
Hi, writing a brain new app is required for linux and there is no plan about such thing so far. You can try a dual boot Windows(10/11)/Linux on the steam deck some Nucleus users did it successfully already.
https://discord.com/channels/142649962839277568/705556112778461284/1024848779079331870
https://discord.com/channels/142649962839277568/705556112778461284/1003304326908878908

**Comment by Snailedlt** [comment]
Relevant issue:
https://github.com/lucasassislar/nucleuscoop/issues/145

**Comment by Natedogwoooof** [comment]
Yeah I do dual built but the bad thing is when I freaking select the windows thing it makes me have to freaking restart the PC going to the stupid freaking recovery menu on Windows just to f****** get back to my daily driver Linux and then I have to navigate the freaking terminal and I have to select Linux bootloader back to the default even though I have grub I hate this annoying

**Comment by Condemnedfate** [comment]
Just commenting to say I would also like to see Linux (and Mac) support. There is unfortunately nothing else like this and being able to play games in split screen would be great for everyone, not just windows users.
