### ISSUE TITLE
proton input failed to runtime inject🐛 <bug name>

### ISSUE THREAD

**Issue by Reaper2001** [SplitScreen-Me/splitscreenme-nucleus#43]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

whenever I try to launch the game call of duty black ops2 it gives me this error on nucleus coop any solution

### Debug Log

whenever I try to launch the game call of duty black ops2 it gives me this error on nucleus coop any solution

**Comment by Mikou27** [comment]
Hi, this is a game specific issue ask for support on the Discord server https://discord.com/invite/QDUt8HpCvr or the subreddit https://www.reddit.com/r/nucleuscoop/ .
