### ISSUE TITLE
Proto input failed to runtime inject

### ISSUE THREAD

**Issue by 404ProgramNotFound** [SplitScreen-Me/splitscreenme-nucleus#5]
i tried to move the folder of nucleus co-op in different paths but all time same error when it try to start game :" Black Ops 2" i tried only zombie

**Comment by Mikou27** [comment]
For handlers issues you contact us and report on the official Nucleus Co-op Subreddit here https://www.reddit.com/r/nucleuscoop/comments/rtd8b0/a_new_year_of_nucleus_coop_dark_souls_3_local/ or on the official discord server here https://discord.gg/E5B6jAX79f
