### ISSUE TITLE
Running a Game (Borderlands 2) via Nucleus resets Win10/11 STTest to "Enabled"🐛 <bug name>

### ISSUE THREAD

**Issue by uniqueum** [SplitScreen-Me/splitscreenme-nucleus#51]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

I understand this might be a bit odd, but bear with me.

I run TranslucentTB in order to make my Windows look nicer. Recent Windows Upgrades have enclosed some functionality for foldable screens or whatnot, so in order for TranslucentTB to work properly the STTest functionality of Win11 has to be disabled ([https://github.com/TranslucentTB/TranslucentTB/issues/672](url)).

Now, as soon as I run a game (in my case Borderlands 2) with Nucleus Co-op and then return to Windows, this functinality is actually reset to enabled -- TranslucentTB stops working properly and I have to re-disable it via ViVeTool.

I do not, at any rate, understand enough of the computer-voodoo-magic that Nucleus is doing in order to know whether this is Nucleus or the handler. Anyway, if somebody could look into it, that'd be much appreciated.

If you need any screenies or a short video, just let me know.

Cheers!

PS: seeing as this problem isn't specific to Nucleus only, but rather to its interactions with the OS, I omitted the Debug. I hope that is okay.

### Debug Log

*

**Comment by Mikou27** [comment]
Hi ,not a Nucleus bug , but probably a Windows Explorer behavior for instance the Borderlands 2 handler suspend explorer.exe when inputs are locked(default End key). You can try to comment this line `Game.LockInputSuspendsExplorer = true;`  in the handler if it's a problem, but unexpected behaviors could get in the way. Hope this help.
