### ISSUE TITLE
Wrong monitor identification/Refusal to assign to correct display.

### ISSUE THREAD

**Issue by LaykaKiro** [SplitScreen-Me/splitscreenme-nucleus#52]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

It seems that Nucleus refuses to identify my two displays correctly whatsoever to a point where no matter what control I set to each display they're always lined up the same way and it's getting on my nerves...
![2023-05-25 10_26_35-Nucleus Co-op](https://github.com/SplitScreen-Me/splitscreenme-nucleus/assets/34409251/12637fa0-2bec-4391-94ee-f7dbdcca4cfe)
It seems to assume my second display is monitor one as well, which is also stupid. Because the bigger display is monitor one.

### Debug Log

Here's your stupid log...
[debug-log.txt](https://github.com/SplitScreen-Me/splitscreenme-nucleus/files/11560089/debug-log.txt)

### Possible fixes or solutions

Allow users to reassign which monitor is display one I guess...

### Additional information

Oh, and the application stops working entirely after both instances are closed. Thought I'd let you know about that too...

**Comment by Mikou27** [comment]
The numbers on the screens in the Nucleus UI indicate the launch order not the Windows graphics settings screen index.

**Comment by LaykaKiro** [comment]
Oh, this was reopened.
