### ISSUE TITLE
✨ Steam Deck / Proton support

### ISSUE THREAD

**Issue by NowInHD-NowInHD** [SplitScreen-Me/splitscreenme-nucleus#55]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

It would be great if this program worked on the Valve Steam Deck, whether that be through proton or natively. 

Currently, there are no options for split-screen for many games on Steam Deck other than begging the developers for it or installing Windows onto the device, which most users won't be able to do due to storage limits (I think the size of Windows is actually larger than the smallest Steam Deck model, 64GB), limited tech knowledge, etc.

The Steam Deck is an amazing console-like device, and as it can be so easily docked to a TV, people are gonna see this as a replacement for a home console and want to play couch-coop with people.

**Comment by Condemnedfate** [comment]
Is there any way to get this reopened/ reconsidered for Linux as a whole, perhaps packaged into an appimage?

**Comment by Snailedlt** [comment]
> Is there any way to get this reopened/ reconsidered for Linux as a whole, perhaps packaged into an appimage?

Nucleus Coop depends on a lot of windows specific API's. Porting the app to Linux, or even Proton would require an almost complete rewrite
