### ISSUE TITLE
ctrl-t is cursed; system wide impact

### ISSUE THREAD

**Issue by mirddes** [SplitScreen-Me/splitscreenme-nucleus#57]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

i thought my computer was broken because i couldn't open new tabs in chrome using ctrl+t
i was going to restart my pc.
firefox also wouldn't open new tabs using ctrl+t
but ctrl+n and ctrl+w worked fine...
and t worked fine on its own...
ruling out possible broken hardware
and then i closed nucleus co-op.....
.....
.....
wasn't even running a game
hadn't even set it up yet.
.....
it broke uix system wide....
not good.
not good at all.

please fix.

### Debug Log

n/a

### Possible fixes or solutions

dont implement in a way that has system wide affects.
dont capture input unless a game is actually running...?!?!?!?

### Additional information

thanks. you're awesome!

**Comment by heliomar-pena** [comment]
Same here. I am using windows 11, not sure if happens on other S.O

**Comment by mirddes** [comment]
It's intentional and considering how many applications it affects it's far
from a sane default

**Comment by Mikou27** [comment]
https://github.com/Mikou27/splitscreenme-nucleus/commit/76ad746593ae4ae9b0309a72a91fdf923662b094 issue will be closed on next Nucleus update.

**Comment by mirddes** [comment]
is this being closed because it's being rebound to sane defaults? or because it's going to get ignored?

**Comment by Mikou27** [comment]
Closed by mistake and reopened right away. Will be enabled only when Nucleus start the game instances and disabled when stopped.

**Comment by mirddes** [comment]
Absolutely beautiful, now that's sane default behaviour.

**Comment by Mister-Curious** [comment]
Similar issues here. This problem is also affecting other things like my horizontal scrolling on my keyboard. After disabling input in Nucleus my horizontal scroll on my Logitech keyboard is completely nuked. Opening Logitech Options to toggle the feature doesn't even fix it. I actually have to close all my applications, save my files, and log out of my computer to get my keyboard to work again. Not fun.

**Comment by Mikou27** [comment]
https://github.com/SplitScreen-Me/splitscreenme-nucleus/releases/tag/v2.3.0.
