### ISSUE TITLE
VR minecraft + normal minecraft🐛 <bug name>

### ISSUE THREAD

**Issue by fireman7q1123** [SplitScreen-Me/splitscreenme-nucleus#58]
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### Bug description

I got vr and normal minecraft to work, running at the same time. For vr all of the buttons except for the left trigger button work and radial menu, so I need to have the left trigger button to work to play. The headset evening work too and of course normal minecraft of the other split screen work as well.

### Debug Log

It won't let me

### Possible fixes or solutions

Making it so the trigger of the oculus touch left controller work with your algorithm.

### Additional information

My vr headset is the oculus quest 2.

**Comment by Mikou27** [comment]
Closed because this is a game specific issue and requires very specific hardware.
