### ISSUE TITLE
Borderlands 3 only supports one controller and one Steam profile🐛 <bug name>

### ISSUE THREAD

**Issue by Djehutimas** [SplitScreen-Me/splitscreenme-nucleus#60]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Borderlands 3 is only supporting on controller and one Steam profile even though I entered the Steam ID of two different profiles 

### Debug Log

Tried putting in to different steam profile IDs and saved them.
I've installed two playstation controllers via bluetooth but it will only support one each at a time on Windows 10

**Comment by Mikou27** [comment]
Ask for game specific support on the Discord server or Reddit.
