### ISSUE TITLE
🐛 Error message "install c++ redistributable" although newest version (x64 AND x86) being installed.

### ISSUE THREAD

**Issue by Nukliar7077** [SplitScreen-Me/splitscreenme-nucleus#66]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Well, the Title tells everything... I just installed the software, no problems with that, upon starting the application (even tried administrator) I just get a message telling me zo install the newest version of C++. I clicked OK and (re) installed both, restarted my PC and started NucleusCoop again. Same error message.

Because I couldn't start the application, there sadly is no log.

### Debug Log

Not avialable / not generated

### Possible fixes or solutions

I didn't install Nucleus and C++ on the C: drive. Could this be a problem?

### Additional information

My System:

Windows 10

I5 2500k
GTX 970
16G DDR3 RAM

**Comment by Mikou27** [comment]
If both x86 and x64 version of latest c++ resistributable has been successfully installed the info message has no reasons to pop-up.
