### ISSUE TITLE
SplashScreen sometimes run endlessly.

### ISSUE THREAD

**Issue by Mikou27** [SplitScreen-Me/splitscreenme-nucleus#7]
Will have to ask to impacted users some details about there hardware configuration.

First config reported lack of details but will be useful for comparisons. 

 Intel Celeron
4 ram
500 ssd i think
64bit 
1700 vram

Did some tests and slow hhd do not impact the splash screen.

**Comment by AtomD5** [comment]
the same happens with me
Core 2 Quad Q9400
4GB DDR3 RAM
GTX 1050

**Comment by dbedggood** [comment]
same issue but it always happens, I have yet to see the app's home screen

Intel Core i5-8300H
8GB DDR4 RAM
NVIDIA GeForce GTX 1060

let me know if there is any more info I can provide

**Comment by AtomD5** [comment]
I solved it by changing "SplashScreen_On" to false in settings.ini

**Comment by Mikou27** [comment]
Can now be kicked by a single click.
