### ISSUE TITLE
key needed

### ISSUE THREAD

**Issue by nnm2217** [SplitScreen-Me/splitscreenme-nucleus#70]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

i installed the nucleus zip file and estracted it but every times it ask for a key for the file "easyhook.dll"
here is the entire message
 "the "easy.hook.dll" file is password protected.
enter your password in the box below"
what should i do?

**Comment by Snailedlt** [comment]
The password for the zip file can be found under the release notes
