### ISSUE TITLE
Mouse and keypad do not work even after locking with the "END" key

### ISSUE THREAD

**Issue by katatin31** [SplitScreen-Me/splitscreenme-nucleus#71]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

I'm trying to play unreal tournament 3. I want to run one instance on keyboard and mouse, and the second on gamepad, but the mouse refuses to work. Looked for an answer on "github" and "reddit", but all answers refer to locking the keyboard and mouse with the "END" key. In my case, the lock doesn't work in any way. I can't spin the camera with the mouse and I can't move around on WASD. If I disable the locks, I can shoot, but I still can't rotate the camera.

https://github.com/SplitScreen-Me/splitscreenme-nucleus/assets/101261355/45a5fe01-a222-43db-a96f-3578a81b9b17

### Debug Log

[debug-log.txt](https://github.com/SplitScreen-Me/splitscreenme-nucleus/files/14896346/debug-log.txt)

### Possible fixes or solutions

Looked for an answer on github and reddit, but all answers refer to locking the keyboard and mouse with the END key. In my case, locking does not work in any way.

**Comment by Mikou27** [comment]
Hi, you can ask for  support on our discord server https://discord.gg/E5B6jAX79f.
