### ISSUE TITLE
🐛 Crashing when launching games in extended display mode / multiple monitors

### ISSUE THREAD

**Issue by abwezi** [SplitScreen-Me/splitscreenme-nucleus#77]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

When I launch games while my desktop is in extended mode with both of my screens running then Nucleus Coop silently crashes within about a second of displaying the "Some handlers will require you to press the end key" window. This does not happen when I only use one monitor. Below are the event viewer logs.
![EVENT 2](https://github.com/SplitScreen-Me/splitscreenme-nucleus/assets/37161583/d75c092c-58fe-4e16-abfa-7f4c11b3566e)
![EVENT 1](https://github.com/SplitScreen-Me/splitscreenme-nucleus/assets/37161583/05457891-4aa4-47c5-94e8-4089326f4f92)

### Debug Log

I have made sure the setting is checked for debug logs and went and reproduced the issue multiple times but when the crash happens there is no debug log generated in the main Nucleus folder, sorry.

**Comment by Mikou27** [comment]
Hi, this is a bug in one of the Windows apis, the workaround is to set the desktop scaling factor to the same value for both screen, ideally 100%.
