### ISSUE TITLE
🐛 <Won't recognize PS5 Dualsense controllers>

### ISSUE THREAD

**Issue by LitttlePigGames** [SplitScreen-Me/splitscreenme-nucleus#80]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

I've connected the PS5 controllers via cable, via bluetooth and even both at the same time and it won't recognize them

### Debug Log

No matter what i do the Debug log won't appear
I can see hidden files
I enabled debug logs in settings

### Additional information

I also tried using a Mario Kart cabled controller licensed by Nintendo

**Comment by LitttlePigGames** [comment]
Looks like the game handler im using won't recognize anything but Xinput

**Comment by Mikou27** [comment]
Not Nucleus related.
