### ISSUE TITLE
🐛 Entering cutscenes mode crashes Nucleus

### ISSUE THREAD

**Issue by einmannlan** [SplitScreen-Me/splitscreenme-nucleus#94]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Since the latest update entering the cutscenes mode crashes nucleus. The Debug log does not show any error, this event is not visible in the log. switching vertical / horizontal works.
Tested with borderlands 3.

### Debug Log

[debug-log.txt](https://github.com/user-attachments/files/17399828/debug-log.txt)

**Comment by Mikou27** [comment]
Did you tried a clean install? https://www.reddit.com/r/nucleuscoop/comments/1g4d7f6/bug_report/

If not please try and let me know.

Edit: Worth to mention that can't reproduce the crash with Borderlands 3.

**Comment by einmannlan** [comment]
> Did you tried a clean install? https://www.reddit.com/r/nucleuscoop/comments/1g4d7f6/bug_report/

I did a clean Install and this solved the issue.
Thanks for the hint!

**Comment by Mikou27** [comment]
Thank you for the feedback, much appreciated.
