### ISSUE TITLE
🐛 Files are pp in new update and can't be extracted

### ISSUE THREAD

**Issue by OS-Atlas** [SplitScreen-Me/splitscreenme-nucleus#95]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

The updater, installer and manual instillation won't extract because the files, including the read me, is password protected.

### Debug Log

na

**Comment by Snailedlt** [comment]
The password is clearly shown in the release notes

**Comment by Mikou27** [comment]
The updater and installer are temporarily disabled because of a bug in the updater. This will be fixed soon in a hotfix. For manual extraction see the SnailedIt answer above.
